version: '3.8'

services:
  db:
    image: mysql:8.3.0
    environment:
      # to run without .env variables
#      MYSQL_DATABASE: test
#      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  wildfly:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
# to run without .env variables
#      DB_CONNECTION_URL: jdbc:mysql://db:3306/test
#      DB_USERNAME: root
#      DB_PASSWORD: password
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    #    healthcheck:
    #      test: ["CMD-SHELL", "curl --fail -I --silent -o /dev/null http://wildfly:8080"]
    #      interval: 5s
    #      timeout: 5s
    #      retries: 20
    restart: unless-stopped
volumes:
  db-data: